FROM jdk8:152

ENV DB_HOST postgres-service
ENV DB_PORT 5432
ENV DB_NAME auradb
ENV DB_USER aura
ENV DB_PASS mysecretpassword
ENV LOGIN_HOST localhost

ARG ARTIFACT_FILENAME

EXPOSE 9000
WORKDIR /home/demo3
COPY ${ARTIFACT_FILENAME} .
RUN useradd -ms /bin/bash demo3
USER demo3
CMD java -jar *.jar