FROM openjdk:8

ARG DB_HOST
ARG DB_PORT
ARG DB_NAME
ARG DB_USER
ARG DB_PASS
ARG LOGIN_HOST=localhost
ARG ARTIFACT_FILENAME

EXPOSE 9000
WORKDIR demo3
COPY "${ARTIFACT_FILENAME}" /
RUN apt-get update && apt-get install -y mc && \
    java -jar "${ARTIFACT_FILENAME}"