FROM postgres:latest

ENV DB_NAME auradb
ENV DB_USER aura
ENV DB_PASS mysecretpassword

ENV POSTGRES_DB ${DB_NAME}
ENV POSTGRES_USER ${DB_USER}
ENV POSTGRES_PASSWORD ${DB_PASS}

EXPOSE 5432
WORKDIR /home/demo3

USER postgres
VOLUME  ["/var/lib/postgresql/data"]

