init_config:
  is_jmx: true
  collect_default_metrics: true

instances:
  - host: localhost
    port: 7199
    user: monitorRole
    password: HtR4!Wb9L*2
#    jmx_url: "service:jmx:rmi:///jndi/rmi://myhost.host:9999/custompath" # optional
#    name: jmx_instance  # optional
#    java_bin_path: /usr/lib/jvm/jdk1.8.0_152/bin/java
#    java_options: "-Xmx200m -Xms50m"
#    trust_store_path: /path/to/trustStore.jks
#    trust_store_password: password
#    process_name_regex: .*process_name.*
#    tools_jar_path: /usr/lib/jvm/jdk1.8.0_152/lib/tools.jar
#    refresh_beans: 60 # optional (in seconds)
#    tags:
#      env: stage
#      newTag: samsara
    conf:
      - include:
          domain: java.lang
          type: MemoryPool
          tags:
              simple: memory_pool
          bean:
            - java.lang:type=MemoryPool,name=Metaspace
            - java.lang:type=MemoryPool,name=Code Cache
          attribute:
            UsageThreshold:
              metric_type: gauge
              alias: jmx.usagethreshold
            Usage.used:
              metric_type: gauge
              alias: jmx.usage.used
      - include:
          domain: java.lang
          tags:
              simple: memory_pool
          bean:
            - java.lang:name=Memory
          attribute:
            HeapMemoryUsage:
              metric_type: gauge
              alias: jmx.heapmemoryusage
            NonHeapMemoryUsage:
              metric_type: gauge
              alias: jmx.nonheapmemoryusage
      - include:
          type: ThreadPool
          attribute:
            maxThreads:
              alias: tomcat.threads.max
              metric_type: gauge
            currentThreadCount:
              alias: tomcat.threads.count
              metric_type: gauge
            currentThreadsBusy:
              alias: tomcat.threads.busy
              metric_type: gauge
      - include:
          type: GlobalRequestProcessor
          attribute:
            bytesSent:
              alias: tomcat.bytes_sent
              metric_type: counter
            bytesReceived:
              alias: tomcat.bytes_rcvd
              metric_type: counter
            errorCount:
              alias: tomcat.error_count
              metric_type: counter
            requestCount:
              alias: tomcat.request_count
              metric_type: counter
            maxTime:
              alias: tomcat.max_time
              metric_type: gauge
            processingTime:
              alias: tomcat.processing_time
              metric_type: counter
      - include:
          j2eeType: Servlet
          attribute:
            processingTime:
              alias: tomcat.servlet.processing_time
              metric_type: counter
            errorCount:
              alias: tomcat.servlet.error_count
              metric_type: counter
            requestCount:
              alias: tomcat.servlet.request_count
              metric_type: counter
      - include:
          type: Cache
          accessCount:
            alias: tomcat.cache.access_count
            metric_type: counter
          hitsCounts:
            alias: tomcat.cache.hits_count
            metric_type: counter
      - include:
          type: JspMonitor
          jspCount:
            alias: tomcat.jsp.count
            metric_type: counter
          jspReloadCount:
            alias: tomcat.jsp.reload_count
            metric_type: counter
#      - include:
#          domain: 2nd_domain
#        exclude:
#          bean:
#            - excluded_bean
#      - include:
#          domain_regex: regex_on_domain
#        exclude:
#          bean_regex:
#            - regex_on_excluded_bean