# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network :forwarded_port, guest: 5432, host: 5432, auto_correct:true
  config.vm.network :forwarded_port, guest: 9000, host: 9000, auto_correct:true

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "../../", "/home/ubuntu/demo1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision "shell" do |shell|
    shell.path = "ansible_init.sh"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbooks/vagrant-playbook-init.yml"
    ansible.raw_arguments = "../.vagrant/machines/default/virtualbox/private_key"
    ansible.raw_arguments = "--vault-password-file=conf/.vault_pass"
    run = "always"
  end

end
