# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.3"

  config.vm.network :forwarded_port, guest: 5432, host: 5432, auto_correct:true
  config.vm.network :forwarded_port, guest: 9000, host: 9000, auto_correct:true

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "../../", "/home/vagrant/demo1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

   config.vm.provision :shell, path: "centos_init.sh"
   config.vm.provision :shell, path: "/bin/python centos_startup.py", run: "always", privileged: true
   
end
