FROM postgres:9.6

ARG DB_NAME=auradb
ARG DB_USER=aura
ARG DB_PASS=mysecretpassword

ENV POSTGRES_DB ${DB_NAME}
ENV POSTGRES_USER ${DB_USER}
ENV POSTGRES_PASSWORD ${DB_PASS}

EXPOSE 5432

WORKDIR /home/demo3

USER root

COPY datadog/create_user.sql /docker-entrypoint-initdb.d/10-create_user.sql

RUN apt-get update -y && \
    apt-get install -y apt-transport-https && \
    sh -c "echo 'deb https://apt.datadoghq.com/ stable main' > /etc/apt/sources.list.d/datadog.list" && \
    apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 C7A7DA52 && \
    apt-get update -y && \
    apt-get install -y datadog-agent \
                    dd-check-postgres

COPY datadog/postgres.yaml /etc/dd-agent/conf.d/postgres.yaml

USER postgres

VOLUME  ["/var/lib/postgresql"]
