FROM postgres:9.6

ARG DB_NAME=auradb
ARG DB_USER=aura
ARG DB_PASS=mysecretpassword

ENV POSTGRES_DB ${DB_NAME}
ENV POSTGRES_USER ${DB_USER}
ENV POSTGRES_PASSWORD ${DB_PASS}

EXPOSE 5432
WORKDIR /home/demo3

USER postgres
VOLUME  ["/var/lib/postgresql"]

