# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network :forwarded_port, guest: 5432, host: 5432, auto_correct:true
  config.vm.network :forwarded_port, guest: 9000, host: 9000, auto_correct:true

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "../../", "/home/ubuntu/demo1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision :shell, path: "vagrant_init.sh"
  config.vm.provision :shell, path: "vagrant_startup.sh", run: "always", privileged: false
   
end
