#!groovy

pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout(
                        [$class: 'GitSCM',
                         branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false,
                         extensions: [[$class: 'CleanBeforeCheckout']],
                         userRemoteConfigs: [[url: 'https://github.com/lerkasan/DevOps028.git']]])
                checkout(
                        [$class: 'GitSCM',
                         branches: [[name: '*jenkins']], doGenerateSubmoduleConfigurations: false,
                         extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'jenkins']],
                         userRemoteConfigs: [[url: 'https://github.com/lerkasan/DevOps028.git']]])
            }
        }
        stage("Test") {
            steps {
                echo "Testing project"
                sh "mvn clean test"
            }
        }
        stage("Prepare RDS and Tomcat") {
            steps {
                parallel (
                        prepare_rds: {
                            echo "Preparing RDS"
                            sh "chmod +x jenkins/jenkins/job-dsl/tomcat/*.sh"
                            sh "chmod +x jenkins/jenkins/infra/tomcat-aws-ami-init.sh"
                            sh "jenkins/jenkins/job-dsl/tomcat/jobdsl-prepare-rds-step.sh"
                        },
                        prepare_tomcat: {
                            echo "Preparing Tomcat"
                            sh "jenkins/jenkins/job-dsl/tomcat/jobdsl-prepare-tomcat-step.sh"
                        }

                )
            }
        }
        stage("Package war") {
            steps {
                echo "Packaging project"
                sh "jenkins/jenkins/job-dsl/tomcat/jobdsl-prebuild-step.sh"
                sh "mvn clean package"
                sh "jenkins/jenkins/job-dsl/tomcat/jobdsl-postbuild-step.sh"
                archive "target/ROOT.war"
            }
        }
        stage("Deploy") {
            steps {
                echo "Deploying to Tomcat"
                unarchive mapping: ["ROOT.war" : "ROOT.war"]
                sh "jenkins/jenkins/job-dsl/tomcat/jobdsl-deploy-step.sh"
            }
        }
    }
}